services:
  minio:
    image: minio/minio:latest
    container_name: minio_virtual_minds
    ports:
      - ${MINIO_API_PORT}:9000   # MinIO API
      - ${MINIO_CONSOLE_PORT}:9001   # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    entrypoint: ["sh", "-c", "minio server /data --console-address ':9001'"]
#    networks:
#      - my_network

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - ${PUSHGATEWAY_PORT}:9091


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - ${PROMETHEUS_PORT}:9090

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - ${PROMETHEUS_ALERT_PORT}:9093


  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - ${INFLUX_DB_PORT}:8086
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./grafana_data:/var/lib/grafana

volumes:
  minio_data:
  influxdb_data:
  grafana_data:

#networks:
#  my_network:
#    driver: bridge