apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000     
  selector:
    app: mlflow-model